# nix/buckconfig.nix — Generate .buckconfig.local from toolchain config
#
# Produces INI sections with Nix store paths for Buck2 toolchains.
# All paths are absolute store paths — hermetic and reproducible.
#
# The `libraries` argument comes from deserialized Dhall (Library.dhall).
# Nix resolves package names → store paths. Dhall is the transport.
{ pkgs, lib, lean4, toolchains, libraries ? { haskell = []; cxx = []; } }:
let
  optional = cond: text: if cond then text else "";

  # LLVM toolchain for C++ (cxx.bzl expects clang, not gcc)
  llvm = pkgs.llvmPackages_19;
  gcc = pkgs.gcc;
  gcc-unwrapped = gcc.cc;
  gcc-version = gcc-unwrapped.version;
  triple = pkgs.stdenv.hostPlatform.config;

  cxxSection = optional toolchains.cxx ''

    [cxx]
    cc = ${llvm.clang}/bin/clang
    cxx = ${llvm.clang}/bin/clang++
    cpp = ${llvm.clang}/bin/clang-cpp
    ar = ${llvm.lld}/bin/llvm-ar
    ld = ${llvm.lld}/bin/ld.lld
    clang_resource_dir = ${llvm.clang}/resource-root
    gcc_include = ${gcc-unwrapped}/include/c++/${gcc-version}
    gcc_include_arch = ${gcc-unwrapped}/include/c++/${gcc-version}/${triple}
    glibc_include = ${pkgs.glibc.dev}/include
    gcc_lib = ${gcc-unwrapped}/lib/gcc/${triple}/${gcc-version}
    gcc_lib_base = ${gcc.cc.lib}/lib
    glibc_lib = ${pkgs.glibc}/lib
  '';

  leanSection = optional toolchains.lean ''

    [lean]
    lean = ${lean4}/bin/lean
    leanc = ${lean4}/bin/leanc
    lean_lib_dir = ${lean4}/lib/lean/library
    lean_include_dir = ${lean4}/include
  '';

  # GHC — with packages from LibSpec.haskell if any, bare otherwise
  haskellPkgNames = libraries.haskell or [];
  ghc = if haskellPkgNames == [] then pkgs.ghc
        else pkgs.haskellPackages.ghcWithPackages (ps:
          map (name: ps.${name}) haskellPkgNames);
  ghcVersion = ghc.version;

  haskellSection = optional toolchains.haskell ''

    [haskell]
    ghc = ${ghc}/bin/ghc
    ghc_pkg = ${ghc}/bin/ghc-pkg
    haddock = ${ghc}/bin/haddock
    ghc_version = ${ghcVersion}
    global_package_db = ${ghc}/lib/ghc-${ghcVersion}/lib/package.conf.d
  '';

  rustSection = optional toolchains.rust ''

    [rust]
    rustc = ${pkgs.rustc}/bin/rustc
    rustdoc = ${pkgs.rustc}/bin/rustdoc
    cargo = ${pkgs.cargo}/bin/cargo
  '';

  nvSection = optional toolchains.cuda (let cuda = pkgs.cudaPackages; in ''

    [nv]
    nvidia_sdk_path = ${cuda.cuda_cudart}
    nvidia_sdk_include = ${cuda.cuda_cudart}/include
    nvidia_sdk_lib = ${cuda.cuda_cudart}/lib
    ptxas = ${cuda.cuda_nvcc}/bin/ptxas
    fatbinary = ${cuda.cuda_nvcc}/bin/fatbinary
    archs = sm_90
    clang = ${llvm.clang}/bin/clang++
  '');

  purescriptSection = optional toolchains.purescript ''

    [purescript]
    purs = ${pkgs.purescript}/bin/purs
    spago = ${pkgs.spago}/bin/spago
    node = ${pkgs.nodejs}/bin/node
  '';

  pythonSection = optional toolchains.python ''

    [python]
    interpreter = ${pkgs.python3}/bin/python3
  '';

  # C++ libraries from LibSpec.cxx — each becomes a [lib.name] section
  # The consumer specifies { name, pkg, libs } entries.
  # Nix resolves pkg to include/lib store paths.
  cxxLibSections = lib.concatMapStrings (entry:
    let
      pkg = pkgs.${entry.pkg};
      # nixpkgs convention: .dev output has headers, base has libs
      includeDir = if pkg ? dev then "${pkg.dev}/include" else "${pkg}/include";
      libDir = "${pkg}/lib";
      libFlags = lib.concatStringsSep " " (entry.libs or []);
    in ''

    [lib.${entry.name}]
    include = ${includeDir}
    lib = ${libDir}
    libs = ${libFlags}
  '') (libraries.cxx or []);

  content = ''
    # AUTO-GENERATED by continuity flake module
    # DO NOT EDIT — nix build .#buckconfig
  '' + cxxSection + leanSection + haskellSection + rustSection
     + nvSection + purescriptSection + pythonSection + cxxLibSections;
in
pkgs.writeText "buckconfig-local" content
