# nix/buckconfig.nix — Generate .buckconfig.local from toolchain config
#
# Produces a text file with Buck2 INI sections containing
# Nix store paths for all enabled toolchains.
{ pkgs, lib, lean4, toolchains }:
let
  optional = cond: text: if cond then text else "";

  cxxSection = optional toolchains.cxx ''

    [cxx]
    cc = ${pkgs.stdenv.cc}/bin/cc
    cxx = ${pkgs.stdenv.cc}/bin/c++
    cpp = ${pkgs.stdenv.cc}/bin/cpp
    ar = ${pkgs.stdenv.cc.bintools.bintools}/bin/ar
    ld = ${pkgs.stdenv.cc.bintools.bintools}/bin/ld
    glibc_include = ${pkgs.glibc.dev}/include
    glibc_lib = ${pkgs.glibc}/lib
  '';

  leanSection = optional toolchains.lean ''

    [lean]
    lean = ${lean4}/bin/lean
    leanc = ${lean4}/bin/leanc
    lean_lib_dir = ${lean4}/lib/lean/library
    lean_include_dir = ${lean4}/include
  '';

  haskellSection = optional toolchains.haskell ''

    [haskell]
    ghc = ${pkgs.ghc}/bin/ghc
    ghc_pkg = ${pkgs.ghc}/bin/ghc-pkg
    haddock = ${pkgs.ghc}/bin/haddock
  '';

  rustSection = optional toolchains.rust ''

    [rust]
    rustc = ${pkgs.rustc}/bin/rustc
    rustdoc = ${pkgs.rustc}/bin/rustdoc
    cargo = ${pkgs.cargo}/bin/cargo
  '';

  nvSection = optional toolchains.cuda (let cuda = pkgs.cudaPackages; in ''

    [nv]
    nvidia_sdk_path = ${cuda.cuda_cudart}
    nvidia_sdk_include = ${cuda.cuda_cudart}/include
    nvidia_sdk_lib = ${cuda.cuda_cudart}/lib
    ptxas = ${cuda.cuda_nvcc}/bin/ptxas
    fatbinary = ${cuda.cuda_nvcc}/bin/fatbinary
    archs = sm_90
  '');

  purescriptSection = optional toolchains.purescript ''

    [purescript]
    purs = ${pkgs.purescript}/bin/purs
    spago = ${pkgs.spago}/bin/spago
    node = ${pkgs.nodejs}/bin/node
  '';

  pythonSection = optional toolchains.python ''

    [python]
    interpreter = ${pkgs.python3}/bin/python3
  '';

  content = ''
    # AUTO-GENERATED by continuity flake module
    # DO NOT EDIT — regenerate with: nix build .#buckconfig
  '' + cxxSection + leanSection + haskellSection + rustSection
     + nvSection + purescriptSection + pythonSection;
in
pkgs.writeText "buckconfig-local" content
