# simdjson example
#
# Requires: simdjson library
# Resolve via .buckconfig.local [cxx] section or pkg-config (TODO).

cxx_binary(
    name = "twitter",
    srcs = ["twitter.cpp"],
    compiler_flags = ["-std=c++20", "-O2"],
    visibility = ["PUBLIC"],
)
