load("@toolchains//:lean.bzl", "lean_binary", "lean_library")

lean_library(
    name = "continuity-lib",
    srcs = [
    "Continuity/Algebra/Grade.lean",
    "Continuity/Build/BzlFile.lean",
    "Continuity/Build/Command.lean",
    "Continuity/Build/Dep.lean",
    "Continuity/Build/Resource.lean",
    "Continuity/Build/Triple.lean",
    "Continuity/Build/Vis.lean",
    "Continuity/Codec/Box.lean",
    "Continuity/Crypto.lean",
    "Continuity/Crypto/SHA256.lean",
    "Continuity/Emit/Cpp/Ast.lean",
    "Continuity/Emit/Dhall/Ast.lean",
    "Continuity/Emit/Haskell/Ast.lean",
    "Continuity/Emit/Starlark/Ast.lean",
    "Continuity/StateMachine.lean",
    "Continuity/Algebra/GradedMonad.lean",
    "Continuity/Build/Library.lean",
    "Continuity/Build/Toolchain.lean",
    "Continuity/Build/Cxx.lean",
    "Continuity/Build/Genrule.lean",
    "Continuity/Build/Haskell.lean",
    "Continuity/Build/Lean4.lean",
    "Continuity/Build/Nv.lean",
    "Continuity/Build/Rust.lean",
    "Continuity/Codec/Bytes.lean",
    "Continuity/Codec/Http2.lean",
    "Continuity/Codec/Scanner.lean",
    "Continuity/Codec/Varint.lean",
    "Continuity/Build/Digest.lean",
    "Continuity/CAS.lean",
    "Continuity/Derivation.lean",
    "Continuity/Emit/Cpp/Render.lean",
    "Continuity/Emit/Dhall/Render.lean",
    "Continuity/Codegen/Codec/Spec.lean",
    "Continuity/Emit/Haskell/Render.lean",
    "Continuity/Emit/Starlark/Render.lean",
    "Continuity/Codegen/Effect.lean",
    "Continuity/Build/Rule.lean",
    "Continuity/Codec/EVM.lean",
    "Continuity/Codec/Git.lean",
    "Continuity/Codec/Guards.lean",
    "Continuity/Codec/Protocol.lean",
    "Continuity/Codec/Zmtp.lean",
    "Continuity/Codec/Dhall/Lexer.lean",
    "Continuity/Codec/Http.lean",
    "Continuity/Codec/Json.lean",
    "Continuity/Codec/Parser.lean",
    "Continuity/Codec/Saml.lean",
    "Continuity/Codec/Http3.lean",
    "Continuity/Codec/Protobuf.lean",
    "Continuity/Build/Action.lean",
    "Continuity/Emit/Cpp/Build.lean",
    "Continuity/Emit/Dhall/Build.lean",
    "Continuity/Codegen/Codec/ToCpp.lean",
    "Continuity/Codegen/Codec/ToHaskell.lean",
    "Continuity/Emit/Haskell/Build.lean",
    "Continuity/Codegen/Build/BzlDefs.lean",
    "Continuity/Codegen/Build/ToStarlark.lean",
    "Continuity/Codec/Limits.lean",
    "Continuity/Codec/GitTransport.lean",
    "Continuity/Codec/Nix.lean",
    "Continuity/Codec/Dhall/Parser.lean",
    "Continuity/REAPI.lean",
    "Continuity/Codegen/Build/ToDhall.lean",
    "Continuity/NAR.lean",
    "Continuity/InitBuck2.lean",
    ],
    deps = [],
)

lean_binary(
    name = "continuity",
    srcs = ["Continuity/Main.lean"],
    deps = [":continuity-lib"],
)
