# toolchains/haskell.bzl — generated by continuity
#
# Haskell toolchain + rules. Builder → AST → Render.

load("@prelude//haskell:toolchain.bzl", "HaskellToolchainInfo", "HaskellPlatformInfo")

MANDATORY_GHC_FLAGS = ["-Wall", "-Werror"]

def _get_ghc() -> str:
    """
    Get GHC from config.
    """
    return read_root_config("haskell", "ghc", "bin/ghc")

def _get_ghc_pkg() -> str:
    """
    Get ghc-pkg from config.
    """
    return read_root_config("haskell", "ghc_pkg", "bin/ghc-pkg")

def _get_package_db() -> str | None:
    """
    Get global package DB.
    """
    return read_root_config("haskell", "global_package_db", None)

HaskellLibraryInfo = provider(fields = {
    "package_name": provider_field(str),
    "hi_dir": provider_field(Artifact | None, default = None),
    "object_dir": provider_field(Artifact | None, default = None),
    "stub_dir": provider_field(Artifact | None, default = None),
    "hie_dir": provider_field(Artifact | None, default = None),
    "objects": provider_field(list, default = []),
    "modules": provider_field(list, default = []),
})

HaskellIncludeInfo = provider(fields = {
    "include_dirs": provider_field(list, default = []),
})

def _haskell_toolchain_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Haskell toolchain with paths from .buckconfig.local.
    """
    ghc = read_root_config("haskell", "ghc", "bin/ghc")
    ghc_pkg = read_root_config("haskell", "ghc_pkg", "bin/ghc-pkg")
    haddock = read_root_config("haskell", "haddock", "bin/haddock")

    return [DefaultInfo(), HaskellToolchainInfo(compiler = ghc, packager = ghc_pkg, linker = ghc, haddock = haddock, compiler_flags = ctx.attrs.compiler_flags, linker_flags = ctx.attrs.linker_flags, ghci_script_template = ctx.attrs.ghci_script_template, ghci_iserv_template = ctx.attrs.ghci_iserv_template, script_template_processor = ctx.attrs.script_template_processor, cache_links = True, archive_contents = "normal", support_expose_package = False), HaskellPlatformInfo(name = "x86_64-linux")]

haskell_toolchain = rule(
    impl = _haskell_toolchain_impl,
    is_toolchain_rule = True,
    attrs = {
        "compiler_flags": attrs.list(attrs.string(), default = []),
        "linker_flags": attrs.list(attrs.string(), default = []),
        "ghci_script_template": attrs.option(attrs.source(), default = None),
        "ghci_iserv_template": attrs.option(attrs.source(), default = None),
        "script_template_processor": attrs.option(attrs.exec_dep(providers = [RunInfo]), default = None),
    },
)

def _haskell_library_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build a Haskell library (.hi + .o + archive).
    """
    ghc = _get_ghc()
    package_db = _get_package_db()

    if not ctx.attrs.srcs:
        return [DefaultInfo(), HaskellLibraryInfo(package_name = ctx.attrs.name, modules = [])]

    obj_dir = ctx.actions.declare_output("objs", dir = True)
    hi_dir = ctx.actions.declare_output("hi", dir = True)
    stub_dir = ctx.actions.declare_output("stubs", dir = True)
    hie_dir = ctx.actions.declare_output("hie", dir = True)

    dep_hi_dirs = []
    dep_libs = []
    dep_sources = []
    for dep in ctx.attrs.deps:
        if HaskellLibraryInfo in dep:
            lib_info = dep[HaskellLibraryInfo]
            if lib_info.hi_dir:
                dep_hi_dirs.append(lib_info.hi_dir)
            if lib_info.objects:
                dep_libs.extend(lib_info.objects)
            else:
                if lib_info.object_dir:
                    dep_libs.append(lib_info.object_dir)
            if lib_info.modules:
                dep_sources.extend(lib_info.modules)

    cmd = cmd_args([ghc])
    cmd.add("-package-env=-")
    cmd.add("-no-link")
    if package_db:
        cmd.add("-package-db", package_db)
    cmd.add(MANDATORY_GHC_FLAGS)
    cmd.add("-XGHC2024")
    for ext in ctx.attrs.language_extensions:
        cmd.add("-X{}".format(ext))
    for pkg in ctx.attrs.packages:
        cmd.add("-package", pkg)
    cmd.add("-odir", obj_dir.as_output())
    cmd.add("-hidir", hi_dir.as_output())
    cmd.add("-stubdir", stub_dir.as_output())
    cmd.add("-fwrite-ide-info")
    cmd.add("-hiedir", hie_dir.as_output())
    cmd.add(ctx.attrs.ghc_options)
    for hi_d in dep_hi_dirs:
        cmd.add(cmd_args("-i", hi_d, delimiter = ""))
    cmd.add(ctx.attrs.srcs)

    ctx.actions.run(cmd, category = "haskell_compile", identifier = ctx.attrs.name)

    # Archive objects
    lib = ctx.actions.declare_output("lib{}.a".format(ctx.attrs.name))
    ar_cmd = cmd_args("/bin/sh", "-c", cmd_args("ar rcs", lib.as_output(), cmd_args(obj_dir, format = "{}/*.o"), delimiter = " "))
    ctx.actions.run(ar_cmd, category = "haskell_archive", identifier = ctx.attrs.name)

    return [DefaultInfo(default_output = lib, sub_targets = {"hi": [DefaultInfo(default_outputs = [hi_dir])], "stubs": [DefaultInfo(default_outputs = [stub_dir])], "objects": [DefaultInfo(default_outputs = [obj_dir])], "hie": [DefaultInfo(default_outputs = [hie_dir])]}), HaskellLibraryInfo(package_name = ctx.attrs.name, hi_dir = hi_dir, object_dir = lib, stub_dir = stub_dir, hie_dir = hie_dir, objects = [], modules = ctx.attrs.srcs)]

haskell_library = rule(
    impl = _haskell_library_impl,
    attrs = {
        "srcs": attrs.list(attrs.source(), default = []),
        "deps": attrs.list(attrs.dep(), default = []),
        "packages": attrs.list(attrs.string(), default = []),
        "ghc_options": attrs.list(attrs.string(), default = []),
        "language_extensions": attrs.list(attrs.string(), default = []),
    },
)

def _haskell_binary_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build a Haskell executable.
    """
    ghc = _get_ghc()
    package_db = _get_package_db()
    out = ctx.actions.declare_output(ctx.attrs.name)
    obj_dir = ctx.actions.declare_output("objs", dir = True)
    hi_dir = ctx.actions.declare_output("hi", dir = True)
    hie_dir = ctx.actions.declare_output("hie", dir = True)

    dep_hi_dirs = []
    dep_libs = []
    dep_sources = []
    for dep in ctx.attrs.deps:
        if HaskellLibraryInfo in dep:
            lib_info = dep[HaskellLibraryInfo]
            if lib_info.hi_dir:
                dep_hi_dirs.append(lib_info.hi_dir)
            if lib_info.objects:
                dep_libs.extend(lib_info.objects)
            else:
                if lib_info.object_dir:
                    dep_libs.append(lib_info.object_dir)
            if lib_info.modules:
                dep_sources.extend(lib_info.modules)

    cmd = cmd_args([ghc])
    cmd.add("-package-env=-")
    if package_db:
        cmd.add("-package-db", package_db)
    cmd.add(MANDATORY_GHC_FLAGS)
    cmd.add("-XGHC2024")
    for ext in ctx.attrs.language_extensions:
        cmd.add("-X{}".format(ext))
    for pkg in ctx.attrs.packages:
        cmd.add("-package", pkg)
    cmd.add("-O2")
    cmd.add("-odir", obj_dir.as_output())
    cmd.add("-hidir", hi_dir.as_output())
    cmd.add("-fwrite-ide-info")
    cmd.add("-hiedir", hie_dir.as_output())
    if ctx.attrs.main:
        cmd.add("-main-is", ctx.attrs.main)
    cmd.add("-o", out.as_output())
    cmd.add(ctx.attrs.ghc_options)
    cmd.add(ctx.attrs.compiler_flags)

    for hi_d in dep_hi_dirs:
        cmd.add(cmd_args("-i", hi_d, delimiter = ""))
    cmd.add(ctx.attrs.srcs)
    cmd.add(dep_sources)
    cmd.add(dep_libs)

    ctx.actions.run(cmd, category = "ghc", identifier = ctx.attrs.name)

    return [DefaultInfo(default_output = out, sub_targets = {"hi": [DefaultInfo(default_outputs = [hi_dir])], "hie": [DefaultInfo(default_outputs = [hie_dir])]}), RunInfo(args = cmd_args(out))]

haskell_binary = rule(
    impl = _haskell_binary_impl,
    attrs = {
        "srcs": attrs.list(attrs.source()),
        "deps": attrs.list(attrs.dep(), default = []),
        "main": attrs.option(attrs.string(), default = None),
        "packages": attrs.list(attrs.string(), default = []),
        "ghc_options": attrs.list(attrs.string(), default = []),
        "language_extensions": attrs.list(attrs.string(), default = []),
        "compiler_flags": attrs.list(attrs.string(), default = []),
    },
)

def _haskell_c_library_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build a C-callable library from Haskell with foreign exports.
    """
    ghc = _get_ghc()
    package_db = _get_package_db()
    stub_dir = ctx.actions.declare_output("stubs", dir = True)
    lib = ctx.actions.declare_output("lib{}.a".format(ctx.attrs.name))

    # Collect dependency hi dirs
    dep_hi_dirs = []
    for dep in ctx.attrs.deps:
        if HaskellLibraryInfo in dep:
            lib_info = dep[HaskellLibraryInfo]
            if lib_info.hi_dir:
                dep_hi_dirs.append(lib_info.hi_dir)

    objects = []
    hi_files = []
    for src in ctx.attrs.srcs:
        src_path = src.short_path
        if src_path.endswith(".hs"):
            base_name = src_path.replace(".hs", "").split("/")[-1]
            obj = ctx.actions.declare_output("{}.o".format(base_name))
            hi = ctx.actions.declare_output("{}.hi".format(base_name))
            cmd = cmd_args([ghc])
            cmd.add("-c", "-package-env=-", "-fPIC")
            if package_db:
                cmd.add("-package-db", package_db)
            cmd.add("-stubdir", stub_dir.as_output())
            cmd.add("-o", obj.as_output())
            cmd.add("-ohi", hi.as_output())
            cmd.add(MANDATORY_GHC_FLAGS)
            cmd.add("-XGHC2024", "-XForeignFunctionInterface")
            for ext in ctx.attrs.language_extensions:
                cmd.add("-X{}".format(ext))
            cmd.add(ctx.attrs.ghc_options)
            for hi_d in dep_hi_dirs:
                cmd.add(cmd_args("-i", hi_d, delimiter = ""))
            for pkg in ctx.attrs.packages:
                cmd.add("-package", pkg)
            cmd.add(src)
            ctx.actions.run(cmd, category = "haskell_compile", identifier = src_path)
            objects.append(obj)
            hi_files.append(hi)

    if not objects:
        return [DefaultInfo()]

    # Archive objects
    ar_cmd = cmd_args("ar", "rcs", lib.as_output())
    ar_cmd.add(objects)
    ctx.actions.run(ar_cmd, category = "haskell_archive", identifier = ctx.attrs.name)

    return [DefaultInfo(default_output = lib), HaskellIncludeInfo(include_dirs = [stub_dir]), HaskellLibraryInfo(package_name = ctx.attrs.name, hi_dir = None, object_dir = lib, stub_dir = stub_dir, objects = objects, modules = [])]

haskell_c_library = rule(
    impl = _haskell_c_library_impl,
    attrs = {
        "srcs": attrs.list(attrs.source(), default = []),
        "deps": attrs.list(attrs.dep(), default = []),
        "packages": attrs.list(attrs.string(), default = ["base"]),
        "ghc_options": attrs.list(attrs.string(), default = []),
        "language_extensions": attrs.list(attrs.string(), default = []),
    },
)

def _haskell_ffi_binary_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build a Haskell binary that calls C/C++ via FFI.
    """
    ghc = _get_ghc()
    cxx = read_root_config("cxx", "cxx", "clang++")
    gcc_include = read_root_config("cxx", "gcc_include", "")
    gcc_include_arch = read_root_config("cxx", "gcc_include_arch", "")
    glibc_include = read_root_config("cxx", "glibc_include", "")
    clang_resource_dir = read_root_config("cxx", "clang_resource_dir", "")
    gcc_lib_base = read_root_config("cxx", "gcc_lib_base", "")
    out = ctx.actions.declare_output(ctx.attrs.name)

    # Compile C++ sources
    cxx_compile_flags = ["-std=c++17", "-O2", "-fPIC", "-c"]
    if gcc_include:
        cxx_compile_flags.extend(["-isystem", gcc_include])
    if gcc_include_arch:
        cxx_compile_flags.extend(["-isystem", gcc_include_arch])
    if glibc_include:
        cxx_compile_flags.extend(["-isystem", glibc_include])
    if clang_resource_dir:
        cxx_compile_flags.extend(["-resource-dir=" + clang_resource_dir])
    cxx_compile_flags.extend(["-I", "."])
    for inc_dir in ctx.attrs.include_dirs:
        cxx_compile_flags.extend(["-I", inc_dir])

    cxx_objects = []
    for src in ctx.attrs.cxx_srcs:
        obj_name = src.short_path.replace(".cpp", ".o").replace(".c", ".o")
        obj = ctx.actions.declare_output(obj_name)
        cmd = cmd_args([cxx] + cxx_compile_flags + ["-o", obj.as_output(), src])
        ctx.actions.run(cmd, category = "cxx_compile", identifier = src.short_path)
        cxx_objects.append(obj)

    # Compile Haskell and link with C++ objects
    obj_dir = ctx.actions.declare_output("hs_objs", dir = True)
    hi_dir = ctx.actions.declare_output("hs_hi", dir = True)
    ghc_cmd = cmd_args([ghc])
    if ctx.attrs.ghc_options:
        ghc_cmd.add(ctx.attrs.ghc_options)
    else:
        ghc_cmd.add("-O2", "-threaded")
    ghc_cmd.add("-odir", obj_dir.as_output())
    ghc_cmd.add("-hidir", hi_dir.as_output())
    ghc_cmd.add(MANDATORY_GHC_FLAGS)
    ghc_cmd.add("-XGHC2024")
    for inc_dir in ctx.attrs.include_dirs:
        if inc_dir:
            ghc_cmd.add("-optc", "-I" + inc_dir)
    if gcc_lib_base:
        ghc_cmd.add("-optl", "-L" + gcc_lib_base)
    for lib_dir in ctx.attrs.extra_lib_dirs:
        if lib_dir:
            ghc_cmd.add("-optl", "-L" + lib_dir)
    for lib in ctx.attrs.extra_libs:
        ghc_cmd.add("-l" + lib)
    ghc_cmd.add("-lstdc++")
    ghc_cmd.add("-o", out.as_output())
    for ext in ctx.attrs.language_extensions:
        ghc_cmd.add("-X{}".format(ext))
    ghc_cmd.add(ctx.attrs.compiler_flags)
    ghc_cmd.add(ctx.attrs.hs_srcs)
    ghc_cmd.add(cxx_objects)
    ctx.actions.run(ghc_cmd, category = "ghc_link", identifier = ctx.attrs.name)

    return [DefaultInfo(default_output = out), RunInfo(args = [out])]

haskell_ffi_binary = rule(
    impl = _haskell_ffi_binary_impl,
    attrs = {
        "hs_srcs": attrs.list(attrs.source()),
        "cxx_srcs": attrs.list(attrs.source(), default = []),
        "cxx_headers": attrs.list(attrs.source(), default = []),
        "deps": attrs.list(attrs.dep(), default = []),
        "packages": attrs.list(attrs.string(), default = []),
        "ghc_options": attrs.list(attrs.string(), default = []),
        "extra_libs": attrs.list(attrs.string(), default = []),
        "extra_lib_dirs": attrs.list(attrs.string(), default = []),
        "include_dirs": attrs.list(attrs.string(), default = []),
        "compiler_flags": attrs.list(attrs.string(), default = []),
        "language_extensions": attrs.list(attrs.string(), default = []),
    },
)

def _haskell_script_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build a single-file Haskell script.
    """
    ghc = _get_ghc()
    out = ctx.actions.declare_output(ctx.attrs.name)
    obj_dir = ctx.actions.declare_output("objs", dir = True)
    hi_dir = ctx.actions.declare_output("hi", dir = True)
    cmd = cmd_args([ghc])
    cmd.add("-odir", obj_dir.as_output())
    cmd.add("-hidir", hi_dir.as_output())
    cmd.add(MANDATORY_GHC_FLAGS)
    cmd.add("-XGHC2024")
    cmd.add(ctx.attrs.compiler_flags)
    cmd.add("-o", out.as_output())
    for inc in ctx.attrs.include_paths:
        cmd.add("-i" + inc)
    for pkg in ctx.attrs.packages:
        cmd.add("-package", pkg)
    cmd.add(ctx.attrs.srcs)
    ctx.actions.run(cmd, category = "haskell_script", identifier = ctx.attrs.name)
    return [DefaultInfo(default_output = out), RunInfo(args = [out])]

haskell_script = rule(
    impl = _haskell_script_impl,
    attrs = {
        "srcs": attrs.list(attrs.source()),
        "include_paths": attrs.list(attrs.string(), default = []),
        "compiler_flags": attrs.list(attrs.string(), default = []),
        "packages": attrs.list(attrs.string(), default = []),
    },
)

haskell_test = rule(
    impl = _haskell_binary_impl,
    attrs = {
        "srcs": attrs.list(attrs.source()),
        "deps": attrs.list(attrs.dep(), default = []),
        "main": attrs.option(attrs.string(), default = None),
        "packages": attrs.list(attrs.string(), default = ["base"]),
        "ghc_options": attrs.list(attrs.string(), default = []),
        "language_extensions": attrs.list(attrs.string(), default = []),
        "compiler_flags": attrs.list(attrs.string(), default = []),
    },
)
