# toolchains/lean.bzl — generated by continuity
#
# Lean 4 compilation rules. Builder → AST → Render.

LeanLibraryInfo = provider(fields = {
    "olean_dir": provider_field(Artifact | None, default = None),
    "c_dir": provider_field(Artifact | None, default = None),
    "lib_name": provider_field(str, default = ""),
    "deps": provider_field(list, default = []),
})

LeanToolchainInfo = provider(fields = {
    "lean": provider_field(str),
    "leanc": provider_field(str),
    "lean_lib_dir": provider_field(str | None, default = None),
    "lean_include_dir": provider_field(str | None, default = None),
})

def _get_lean() -> str | None:
    """
    Get lean from config.
    """
    path = read_root_config("lean", "lean", None)
    if path == None:
        fail("""
lean compiler not configured.
Configure via Nix .buckconfig.local [lean] section.
""")
    return path

def _get_leanc() -> str | None:
    """
    Get leanc from config.
    """
    path = read_root_config("lean", "leanc", None)
    if path == None:
        fail("""leanc not configured. See [lean] section in .buckconfig""")
    return path

def _get_lean_lib_dir() -> str | None:
    """
    Get Lean standard library directory.
    """
    return read_root_config("lean", "lean_lib_dir", None)

def _get_lean_include_dir() -> str | None:
    """
    Get Lean C headers directory.
    """
    return read_root_config("lean", "lean_include_dir", None)

def _lean_library_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build a Lean library (.olean files).
    """
    lean = _get_lean()
    lean_lib_dir = _get_lean_lib_dir()

    if not ctx.attrs.srcs:
        return [DefaultInfo(), LeanLibraryInfo()]

    olean_dir = ctx.actions.declare_output("olean", dir = True)
    c_dir = ctx.actions.declare_output("c", dir = True) if ctx.attrs.extract_c else None

    # Collect dependency olean directories
    dep_paths = []
    for dep in ctx.attrs.deps:
        if LeanLibraryInfo in dep:
            info = dep[LeanLibraryInfo]
            if info.olean_dir:
                dep_paths.append(info.olean_dir)

    script_parts = ["set -e"]
    script_parts.append("mkdir -p $OLEAN_DIR")
    if c_dir:
        script_parts.append("mkdir -p $C_DIR")

    # Build LEAN_PATH
    lean_path_parts = ["$OLEAN_DIR"]
    if lean_lib_dir:
        lean_path_parts.append(lean_lib_dir)
    for dep_path in dep_paths:
        lean_path_parts.append(cmd_args(dep_path))
    script_parts.append(cmd_args("export LEAN_PATH=", cmd_args(lean_path_parts, delimiter = ":"), delimiter = ""))

    # Compile each source
    for src in ctx.attrs.srcs:
        # Preserve directory structure for hierarchical modules
        src_path = src.short_path
        olean_path = src_path.removesuffix(".lean") + ".olean"
        script_parts.append(cmd_args("mkdir -p $(dirname $BUCK_SCRATCH_PATH/", src_path, ")", delimiter = ""))
        script_parts.append(cmd_args("cp", src, cmd_args("$BUCK_SCRATCH_PATH/", src_path, delimiter = ""), delimiter = " "))
        script_parts.append(cmd_args("mkdir -p $(dirname $OLEAN_DIR/", olean_path, ")", delimiter = ""))
        compile_cmd = [lean, "--root=$BUCK_SCRATCH_PATH"]
        compile_cmd.extend(ctx.attrs.lean_flags)
        compile_cmd.extend(["-o", cmd_args("$OLEAN_DIR/", olean_path, delimiter = "")])
        if c_dir:
            c_path = src_path.removesuffix(".lean") + ".c"
            script_parts.append(cmd_args("mkdir -p $(dirname $C_DIR/", c_path, ")", delimiter = ""))
            compile_cmd.append(cmd_args("--c=$C_DIR/", c_path, delimiter = ""))
        compile_cmd.append(cmd_args("$BUCK_SCRATCH_PATH/", src_path, delimiter = ""))
        script_parts.append(cmd_args(compile_cmd, delimiter = " "))

    script = cmd_args(script_parts, delimiter = "\n")
    env_parts = ["OLEAN_DIR=", olean_dir.as_output()]
    if c_dir:
        env_parts.extend([" C_DIR=", c_dir.as_output()])
    cmd = cmd_args("/bin/sh", "-c", cmd_args(env_parts, " && ", script, delimiter = ""))

    hidden = list(ctx.attrs.srcs)
    for dep_path in dep_paths:
        hidden.append(dep_path)
    ctx.actions.run(cmd_args(cmd, hidden = hidden), category = "lean_compile", identifier = ctx.attrs.name, local_only = True)

    return [DefaultInfo(default_output = olean_dir), LeanLibraryInfo(olean_dir = olean_dir, c_dir = c_dir, lib_name = ctx.attrs.name, deps = ctx.attrs.deps)]

lean_library = rule(
    impl = _lean_library_impl,
    attrs = {
        "srcs": attrs.list(attrs.source(), default = []),
        "deps": attrs.list(attrs.dep(), default = []),
        "lean_flags": attrs.list(attrs.string(), default = []),
        "extract_c": attrs.bool(default = False),
    },
)

def _lean_binary_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build a Lean executable with hierarchical module support.
    """
    lean = _get_lean()
    leanc = _get_leanc()
    lean_lib_dir = _get_lean_lib_dir()

    if not ctx.attrs.srcs:
        fail("lean_binary requires at least one source file")

    # Output
    exe = ctx.actions.declare_output(ctx.attrs.name)
    olean_dir = ctx.actions.declare_output("olean", dir = True)
    c_dir = ctx.actions.declare_output("c", dir = True)

    # Collect dependency olean directories
    dep_paths = []
    for dep in ctx.attrs.deps:
        if LeanLibraryInfo in dep:
            info = dep[LeanLibraryInfo]
            if info.olean_dir:
                dep_paths.append(info.olean_dir)

    # Build LEAN_PATH
    lean_path_parts = ["$OLEAN_DIR", "$BUCK_SCRATCH_PATH"]
    if lean_lib_dir:
        lean_path_parts.append(lean_lib_dir)
    for dep_path in dep_paths:
        lean_path_parts.append(cmd_args(dep_path))

    # Build script: compile each source to C, then link with leanc
    script_parts = ["set -e"]
    script_parts.append("mkdir -p $OLEAN_DIR $C_DIR")

    script_parts.append(cmd_args("export LEAN_PATH=", cmd_args(lean_path_parts, delimiter = ":"), delimiter = ""))

    # Determine module structure
    root_module = ctx.attrs.root_module
    c_files = []
    compile_order = []
    main_src = None

    for src in ctx.attrs.srcs:
        if src.basename == "Main.lean":
            main_src = src
        else:
            compile_order.append(src)
    if main_src:
        compile_order.append(main_src)
    else:
        main_src = ctx.attrs.srcs[0]

    if root_module:
        script_parts.append("mkdir -p $BUCK_SCRATCH_PATH/{}".format(root_module))

    # Copy and compile each source
    for src in compile_order:
        module_name = src.basename.removesuffix(".lean")

        if root_module and src.basename != "Main.lean":
            dest_path = "$BUCK_SCRATCH_PATH/{}/{}".format(root_module, src.basename)
            c_file = "$C_DIR/{}.{}.c".format(root_module, module_name)
            olean_file = "$OLEAN_DIR/{}/{}.olean".format(root_module, module_name)
            script_parts.append("mkdir -p $OLEAN_DIR/{}".format(root_module))
        else:
            dest_path = "$BUCK_SCRATCH_PATH/{}".format(src.basename)
            c_file = "$C_DIR/{}.c".format(module_name)
            olean_file = "$OLEAN_DIR/{}.olean".format(module_name)
        c_files.append(c_file)
        script_parts.append(cmd_args("cp", src, dest_path, delimiter = " "))
        compile_cmd = [lean, "--root=$BUCK_SCRATCH_PATH", "-o", olean_file, cmd_args("--c=", c_file, delimiter = "")]
        compile_cmd.extend(ctx.attrs.lean_flags)
        compile_cmd.append(dest_path)
        script_parts.append(cmd_args(compile_cmd, delimiter = " "))

    # Link with leanc
    link_cmd = [leanc, "-o", exe.as_output()]
    link_cmd.extend(ctx.attrs.link_flags)
    for c_file in c_files:
        link_cmd.append(c_file)
    script_parts.append(cmd_args(link_cmd, delimiter = " "))

    script = cmd_args(script_parts, delimiter = "\n")
    cmd = cmd_args("/bin/sh", "-c", cmd_args("OLEAN_DIR=", olean_dir.as_output(), " C_DIR=", c_dir.as_output(), " && ", script, delimiter = ""))

    hidden = list(ctx.attrs.srcs)
    hidden.extend(dep_paths)

    ctx.actions.run(cmd_args(cmd, hidden = hidden), category = "lean_link", identifier = ctx.attrs.name, local_only = True)

    return [DefaultInfo(default_output = exe), RunInfo(args = cmd_args(exe))]

lean_binary = rule(
    impl = _lean_binary_impl,
    attrs = {
        "srcs": attrs.list(attrs.source(), default = []),
        "deps": attrs.list(attrs.dep(), default = []),
        "root_module": attrs.option(attrs.string(), default = None),
        "lean_flags": attrs.list(attrs.string(), default = []),
        "link_flags": attrs.list(attrs.string(), default = []),
    },
)

def _lean_toolchain_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Lean toolchain with paths from .buckconfig.local.
    """
    # Read from config, fall back to attrs
    lean = read_root_config("lean", "lean", ctx.attrs.lean)
    leanc = read_root_config("lean", "leanc", ctx.attrs.leanc)
    lean_lib_dir = read_root_config("lean", "lean_lib_dir", ctx.attrs.lean_lib_dir)
    lean_include_dir = read_root_config("lean", "lean_include_dir", ctx.attrs.lean_include_dir)

    return [DefaultInfo(), LeanToolchainInfo(lean = lean, leanc = leanc, lean_lib_dir = lean_lib_dir, lean_include_dir = lean_include_dir)]

lean_toolchain = rule(
    impl = _lean_toolchain_impl,
    is_toolchain_rule = True,
    attrs = {
        "lean": attrs.string(default = "lean"),
        "leanc": attrs.string(default = "leanc"),
        "lean_lib_dir": attrs.option(attrs.string(), default = None),
        "lean_include_dir": attrs.option(attrs.string(), default = None),
    },
)
