# toolchains/nv.bzl — generated by continuity
#
# NVIDIA toolchain using clang (NOT nvcc). Builder → AST → Render.
# "nv" not "cuda" — explicit about the target hardware.

NvToolchainInfo = provider(fields = {
    "nvidia_sdk_path": provider_field(str),
    "nvidia_sdk_include": provider_field(str),
    "nvidia_sdk_lib": provider_field(str),
    "nv_archs": provider_field(list[str]),
})

def _nv_toolchain_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    NVIDIA toolchain with paths from .buckconfig.local.
    """
    nvidia_sdk_path = read_root_config("nv", "nvidia_sdk_path", ctx.attrs.nvidia_sdk_path)
    nvidia_sdk_include = read_root_config("nv", "nvidia_sdk_include", ctx.attrs.nvidia_sdk_include)
    nvidia_sdk_lib = read_root_config("nv", "nvidia_sdk_lib", ctx.attrs.nvidia_sdk_lib)

    return [DefaultInfo(), NvToolchainInfo(nvidia_sdk_path = nvidia_sdk_path, nvidia_sdk_include = nvidia_sdk_include, nvidia_sdk_lib = nvidia_sdk_lib, nv_archs = ctx.attrs.nv_archs)]

nv_toolchain = rule(
    impl = _nv_toolchain_impl,
    is_toolchain_rule = True,
    attrs = {
        "nv_archs": attrs.list(attrs.string(), default = ["sm_90"]),
        "nvidia_sdk_path": attrs.string(default = "/usr/local/cuda"),
        "nvidia_sdk_include": attrs.string(default = "/usr/local/cuda/include"),
        "nvidia_sdk_lib": attrs.string(default = "/usr/local/cuda/lib64"),
    },
)

def _nv_binary_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build an NVIDIA binary using clang (NOT nvcc).
    """
    # Validate CUDA toolchain
    clang = read_root_config("nv", "clang", None)
    if clang == None:
        fail("""
NVIDIA toolchain not configured.
Enable CUDA in your flake:
    continuity.toolchains.cuda = true;
Then: direnv reload
""")
    nvidia_sdk_path = read_root_config("nv", "nvidia_sdk_path", "/usr/local/cuda")
    nvidia_sdk_include = read_root_config("nv", "nvidia_sdk_include", "/usr/local/cuda/include")
    nvidia_sdk_lib = read_root_config("nv", "nvidia_sdk_lib", "/usr/local/cuda/lib64")
    ptxas = read_root_config("nv", "ptxas", "")
    gcc_include = read_root_config("cxx", "gcc_include", "")
    gcc_include_arch = read_root_config("cxx", "gcc_include_arch", "")
    glibc_include = read_root_config("cxx", "glibc_include", "")
    clang_resource_dir = read_root_config("cxx", "clang_resource_dir", "")
    nv_archs_str = read_root_config("nv", "archs", "sm_90")
    nv_archs = nv_archs_str.split(",")
    gcc_lib = read_root_config("cxx", "gcc_lib", "")
    gcc_lib_base = read_root_config("cxx", "gcc_lib_base", "")
    glibc_lib = read_root_config("cxx", "glibc_lib", "")
    ld = read_root_config("cxx", "ld", "ld.lld")
    mdspan_include = read_root_config("nv", "mdspan_include", "")

    compile_flags = ["-x", "cuda", "--cuda-path=" + nvidia_sdk_path, "-isystem", nvidia_sdk_include, "-std=c++23", "-c"]
    if ptxas:
        compile_flags.extend(["--ptxas-path=" + ptxas])
    for arch in nv_archs:
        compile_flags.extend(["--cuda-gpu-arch=" + arch.strip()])
        compile_flags.extend(["--cuda-include-ptx=" + arch.strip()])
    if clang_resource_dir:
        compile_flags.extend(["-resource-dir=" + clang_resource_dir])
    if gcc_include:
        compile_flags.extend(["-isystem", gcc_include])
    if gcc_include_arch:
        compile_flags.extend(["-isystem", gcc_include_arch])
    if glibc_include:
        compile_flags.extend(["-isystem", glibc_include])
    compile_flags.append("-Wno-unknown-cuda-version")
    if mdspan_include:
        compile_flags.extend(["-isystem", mdspan_include])

    objects = []
    for src in ctx.attrs.srcs:
        obj_name = src.short_path.replace(".cu", ".o").replace(".cpp", ".o")
        obj = ctx.actions.declare_output(obj_name)
        cmd = cmd_args([clang] + compile_flags + ["-o", obj.as_output(), src])
        ctx.actions.run(cmd, category = "nv_compile", identifier = src.short_path)
        objects.append(obj)

    # Link
    link_flags = ["-fuse-ld=" + ld, "-L" + nvidia_sdk_lib, "-Wl,-rpath," + nvidia_sdk_lib, "-lcudart"]
    if gcc_lib:
        link_flags.extend(["-B" + gcc_lib, "-L" + gcc_lib])
    if gcc_lib_base:
        link_flags.extend(["-L" + gcc_lib_base, "-Wl,-rpath," + gcc_lib_base])
    if glibc_lib:
        link_flags.extend(["-B" + glibc_lib, "-L" + glibc_lib, "-Wl,-rpath," + glibc_lib, "-Wl,--dynamic-linker=" + glibc_lib + "/ld-linux-x86-64.so.2"])
    out = ctx.actions.declare_output(ctx.attrs.name)
    link_cmd = cmd_args([clang] + link_flags + ["-o", out.as_output()])
    link_cmd.add(objects)
    ctx.actions.run(link_cmd, category = "nv_link", identifier = ctx.attrs.name)

    return [DefaultInfo(default_output = out), RunInfo(args = cmd_args([out]))]

nv_binary = rule(
    impl = _nv_binary_impl,
    attrs = {
        "srcs": attrs.list(attrs.source()),
        "deps": attrs.list(attrs.dep(), default = []),
    },
)

NvLibraryInfo = provider(fields = {
    "objects": provider_field(list),
    "headers": provider_field(list),
    "include_dir": provider_field(str),
})

def _nv_library_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Compile CUDA sources into object files.
    """
    # Validate CUDA toolchain
    clang = read_root_config("nv", "clang", None)
    if clang == None:
        fail("""
NVIDIA toolchain not configured.
Enable CUDA in your flake:
    continuity.toolchains.cuda = true;
Then: direnv reload
""")
    nvidia_sdk_path = read_root_config("nv", "nvidia_sdk_path", "/usr/local/cuda")
    nvidia_sdk_include = read_root_config("nv", "nvidia_sdk_include", "/usr/local/cuda/include")
    nvidia_sdk_lib = read_root_config("nv", "nvidia_sdk_lib", "/usr/local/cuda/lib64")
    ptxas = read_root_config("nv", "ptxas", "")
    gcc_include = read_root_config("cxx", "gcc_include", "")
    gcc_include_arch = read_root_config("cxx", "gcc_include_arch", "")
    glibc_include = read_root_config("cxx", "glibc_include", "")
    clang_resource_dir = read_root_config("cxx", "clang_resource_dir", "")
    nv_archs_str = read_root_config("nv", "archs", "sm_90")
    nv_archs = nv_archs_str.split(",")

    compile_flags = ["-x", "cuda", "--cuda-path=" + nvidia_sdk_path, "-isystem", nvidia_sdk_include, "-std=c++17", "-c"]
    if ptxas:
        compile_flags.extend(["--ptxas-path=" + ptxas])
    for arch in nv_archs:
        compile_flags.extend(["--cuda-gpu-arch=" + arch.strip()])
        compile_flags.extend(["--cuda-include-ptx=" + arch.strip()])
    if clang_resource_dir:
        compile_flags.extend(["-resource-dir=" + clang_resource_dir])
    if gcc_include:
        compile_flags.extend(["-isystem", gcc_include])
    if gcc_include_arch:
        compile_flags.extend(["-isystem", gcc_include_arch])
    if glibc_include:
        compile_flags.extend(["-isystem", glibc_include])
    compile_flags.append("-fPIC")

    objects = []
    for src in ctx.attrs.srcs:
        obj_name = src.short_path.replace(".cu", ".o").replace(".cpp", ".o")
        obj = ctx.actions.declare_output(obj_name)
        cmd = cmd_args([clang] + compile_flags + ["-o", obj.as_output(), src])
        ctx.actions.run(cmd, category = "nv_compile", identifier = src.short_path)
        objects.append(obj)

    include_dir = ""
    if ctx.attrs.exported_headers:
        first_header = ctx.attrs.exported_headers[0]
        if "/" in first_header.short_path:
            include_dir = first_header.short_path.rsplit("/", 1)[0]
        else:
            include_dir = "."

    return [DefaultInfo(default_output = objects[0] if objects else None, other_outputs = objects[1:] if len(objects) > 1 else []), NvLibraryInfo(objects = objects, headers = ctx.attrs.exported_headers, include_dir = include_dir)]

nv_library = rule(
    impl = _nv_library_impl,
    attrs = {
        "srcs": attrs.list(attrs.source()),
        "exported_headers": attrs.list(attrs.source(), default = []),
        "deps": attrs.list(attrs.dep(), default = []),
    },
)
