# toolchains/purescript.bzl — generated by continuity
#
# PureScript compilation rules. Builder → AST → Render.

PureScriptLibraryInfo = provider(fields = {
    "output_dir": provider_field(Artifact | None, default = None),
    "lib_name": provider_field(str, default = ""),
    "deps": provider_field(list, default = []),
})

PureScriptToolchainInfo = provider(fields = {
    "purs": provider_field(str),
    "spago": provider_field(str | None, default = None),
    "node": provider_field(str | None, default = None),
})

def _get_purs() -> str:
    """
    Get purs from config.
    """
    path = read_root_config("purescript", "purs", None)
    if path == None:
        fail("""
purs not configured.
Enable in flake: continuity.toolchains.purescript = true;
Then: direnv reload
""")
    return path

def _get_spago() -> str:
    """
    Get spago from config.
    """
    path = read_root_config("purescript", "spago", None)
    if path == None:
        fail("spago not configured. See [purescript] in .buckconfig")
    return path

def _get_node() -> str:
    """
    Get node from config.
    """
    return read_root_config("purescript", "node", "node")

def _get_esbuild() -> str | None:
    """
    Get esbuild (optional).
    """
    return read_root_config("purescript", "esbuild", None)

def _purescript_app_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build a PureScript web application with spago.
    """
    purs = _get_purs()
    spago = _get_spago()
    node = _get_node()

    if not ctx.attrs.srcs:
        fail("purescript_app requires at least one source file")
    dist_dir = ctx.actions.declare_output("dist", dir = True)
    script_parts = ["set -e"]

    # Set up PATH for spago to find purs
    esbuild = _get_esbuild()
    if esbuild:
        script_parts.append("export PATH=\"$(dirname {})\":\"$(dirname {})\":$PATH".format(purs, esbuild))
    else:
        script_parts.append("export PATH=\"$(dirname {})\":$PATH".format(purs))
    script_parts.append("WORK_DIR=$BUCK_SCRATCH_PATH/work")
    script_parts.append("mkdir -p $WORK_DIR/src/Component")

    # Copy spago config
    if ctx.attrs.spago_yaml:
        script_parts.append(cmd_args("cp ", ctx.attrs.spago_yaml, " $WORK_DIR/spago.yaml", delimiter = ""))
    if ctx.attrs.spago_dhall:
        script_parts.append(cmd_args("cp ", ctx.attrs.spago_dhall, " $WORK_DIR/spago.dhall", delimiter = ""))

    # Copy sources preserving structure
    for src in ctx.attrs.srcs:
        script_parts.append(cmd_args("mkdir -p \"$WORK_DIR/$(dirname ", src, ")\" && cp ", src, " \"$WORK_DIR/", src, "\"", delimiter = ""))

    # Build and bundle
    script_parts.append("cd $WORK_DIR")
    script_parts.append(cmd_args(spago, " build", delimiter = ""))
    script_parts.append(cmd_args(spago, " bundle", delimiter = ""))
    script_parts.append("cd -")

    # Assemble dist
    script_parts.append(cmd_args("mkdir -p ", dist_dir.as_output(), delimiter = ""))
    script_parts.append(cmd_args("cp $WORK_DIR/app.js ", dist_dir.as_output(), "/app.js", delimiter = ""))
    if ctx.attrs.index_html:
        script_parts.append(cmd_args("cp ", ctx.attrs.index_html, " ", dist_dir.as_output(), "/index.html", delimiter = ""))
    if ctx.attrs.style_css:
        script_parts.append(cmd_args("cp ", ctx.attrs.style_css, " ", dist_dir.as_output(), "/style.css", delimiter = ""))

    script = cmd_args(script_parts, delimiter = "\n")
    cmd = cmd_args("/bin/sh", "-c", script)

    hidden = list(ctx.attrs.srcs)
    if ctx.attrs.spago_yaml:
        hidden.append(ctx.attrs.spago_yaml)
    if ctx.attrs.spago_dhall:
        hidden.append(ctx.attrs.spago_dhall)
    if ctx.attrs.index_html:
        hidden.append(ctx.attrs.index_html)
    if ctx.attrs.style_css:
        hidden.append(ctx.attrs.style_css)

    ctx.actions.run(cmd_args(cmd, hidden = hidden), category = "spago_bundle", identifier = ctx.attrs.name, local_only = True)

    return [DefaultInfo(default_output = dist_dir), RunInfo(args = cmd_args(dist_dir))]

purescript_app = rule(
    impl = _purescript_app_impl,
    attrs = {
        "srcs": attrs.list(attrs.source(), default = []),
        "spago_yaml": attrs.option(attrs.source(), default = None),
        "spago_dhall": attrs.option(attrs.source(), default = None),
        "main": attrs.string(default = "Main"),
        "index_html": attrs.option(attrs.source(), default = None),
        "style_css": attrs.option(attrs.source(), default = None),
    },
)

def _purescript_toolchain_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    PureScript toolchain with paths from .buckconfig.local.
    """
    purs = read_root_config("purescript", "purs", ctx.attrs.purs)
    spago = read_root_config("purescript", "spago", ctx.attrs.spago)
    node = read_root_config("purescript", "node", ctx.attrs.node)
    return [DefaultInfo(), PureScriptToolchainInfo(purs = purs, spago = spago, node = node)]

purescript_toolchain = rule(
    impl = _purescript_toolchain_impl,
    is_toolchain_rule = True,
    attrs = {
        "purs": attrs.string(default = "purs"),
        "spago": attrs.option(attrs.string(), default = None),
        "node": attrs.option(attrs.string(), default = None),
    },
)
