# toolchains/rust.bzl — generated by continuity
#
# Hermetic Rust toolchain + rules. Builder → AST → Render.

load("@prelude//rust:rust_toolchain.bzl", "PanicRuntime", "RustToolchainInfo")

RustCrateInfo = provider(fields = {
    "rlib": provider_field(Artifact),
    "rmeta": provider_field(Artifact | None, default = None),
    "crate_name": provider_field(str),
})

RustLibraryInfo = provider(fields = {
    "rlib": provider_field(Artifact),
    "crate_name": provider_field(str),
    "transitive_deps": provider_field(list, default = []),
})

def _rust_toolchain_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Rust toolchain with paths from .buckconfig.local.
    """
    rustc = read_root_config("rust", "rustc", "rustc")
    rustdoc = read_root_config("rust", "rustdoc", "rustdoc")
    clippy_driver = read_root_config("rust", "clippy_driver", "clippy-driver")
    target_triple = read_root_config("rust", "target_triple", "x86_64-unknown-linux-gnu")

    return [DefaultInfo(), RustToolchainInfo(compiler = RunInfo(args = [rustc]), rustdoc = RunInfo(args = [rustdoc]), clippy_driver = RunInfo(args = [clippy_driver]), rustc_target_triple = target_triple, default_edition = ctx.attrs.default_edition, panic_runtime = PanicRuntime(ctx.attrs.panic_runtime), rustc_flags = ctx.attrs.rustc_flags, rustc_binary_flags = ctx.attrs.rustc_binary_flags, rustc_test_flags = ctx.attrs.rustc_test_flags, rustdoc_flags = ctx.attrs.rustdoc_flags, allow_lints = ctx.attrs.allow_lints, deny_lints = ctx.attrs.deny_lints, warn_lints = ctx.attrs.warn_lints, report_unused_deps = ctx.attrs.report_unused_deps, doctests = ctx.attrs.doctests)]

rust_toolchain = rule(
    impl = _rust_toolchain_impl,
    is_toolchain_rule = True,
    attrs = {
        "default_edition": attrs.string(default = "2021"),
        "panic_runtime": attrs.string(default = "unwind"),
        "rustc_flags": attrs.list(attrs.string(), default = []),
        "rustc_binary_flags": attrs.list(attrs.string(), default = []),
        "rustc_test_flags": attrs.list(attrs.string(), default = []),
        "rustdoc_flags": attrs.list(attrs.string(), default = []),
        "allow_lints": attrs.list(attrs.string(), default = []),
        "deny_lints": attrs.list(attrs.string(), default = []),
        "warn_lints": attrs.list(attrs.string(), default = []),
        "report_unused_deps": attrs.bool(default = False),
        "doctests": attrs.bool(default = False),
    },
)

def _rust_binary_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build a Rust binary.
    """
    rustc = read_root_config("rust", "rustc", "rustc")
    out = ctx.actions.declare_output(ctx.attrs.name)
    cmd = cmd_args([rustc])
    cmd.add("--edition", ctx.attrs.edition)
    cmd.add("-O")
    cmd.add("-o", out.as_output())

    # Collect deps (rlibs)
    for dep in ctx.attrs.deps:
        if RustLibraryInfo in dep:
            lib_info = dep[RustLibraryInfo]
            cmd.add(cmd_args("--extern", cmd_args(lib_info.crate_name, "=", lib_info.rlib, delimiter = "")))
            cmd.add(cmd_args(lib_info.rlib, format = "-Ldependency={}", parent = 1))
            for trans_rlib in lib_info.transitive_deps:
                cmd.add(cmd_args(trans_rlib, format = "-Ldependency={}", parent = 1))

    # Binary root is the first source file
    if ctx.attrs.srcs:
        cmd.add(ctx.attrs.srcs[0])
        if len(ctx.attrs.srcs) > 1:
            cmd.add(cmd_args(hidden = ctx.attrs.srcs[1:]))

    ctx.actions.run(cmd, category = "rustc")

    return [DefaultInfo(default_output = out), RunInfo(args = cmd_args(out))]

rust_binary = rule(
    impl = _rust_binary_impl,
    attrs = {
        "srcs": attrs.list(attrs.source()),
        "deps": attrs.list(attrs.dep(), default = []),
        "edition": attrs.string(default = "2021"),
    },
)

def _rust_library_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Build a Rust library (rlib).
    """
    rustc = read_root_config("rust", "rustc", "rustc")
    crate_name = ctx.attrs.crate_name or ctx.attrs.name

    if ctx.attrs.proc_macro:
        out = ctx.actions.declare_output("lib{}.so".format(crate_name))
        crate_type = "proc-macro"
    else:
        out = ctx.actions.declare_output("lib{}.rlib".format(crate_name))
        crate_type = "rlib"

    cmd = cmd_args([rustc])
    cmd.add("--crate-type", crate_type)
    cmd.add("--crate-name", crate_name)
    cmd.add("--edition", ctx.attrs.edition)
    cmd.add("-O")
    cmd.add("-o", out.as_output())

    if ctx.attrs.proc_macro:
        cmd.add("--extern", "proc_macro")
    for feature in ctx.attrs.features:
        cmd.add("--cfg", "feature=\"{}\"".format(feature))

    transitive_deps = []
    for dep in ctx.attrs.deps:
        if RustLibraryInfo in dep:
            lib_info = dep[RustLibraryInfo]
            cmd.add(cmd_args("--extern", cmd_args(lib_info.crate_name, "=", lib_info.rlib, delimiter = "")))
            cmd.add(cmd_args(lib_info.rlib, format = "-Ldependency={}", parent = 1))
            transitive_deps.append(lib_info.rlib)
            for trans_rlib in lib_info.transitive_deps:
                cmd.add(cmd_args(trans_rlib, format = "-Ldependency={}", parent = 1))
                transitive_deps.append(trans_rlib)

    if ctx.attrs.srcs:
        cmd.add(ctx.attrs.srcs[0])
        if len(ctx.attrs.srcs) > 1:
            cmd.add(cmd_args(hidden = ctx.attrs.srcs[1:]))

    ctx.actions.run(cmd, category = "rustc")

    return [DefaultInfo(default_output = out), RustLibraryInfo(rlib = out, crate_name = crate_name, transitive_deps = transitive_deps)]

rust_library = rule(
    impl = _rust_library_impl,
    attrs = {
        "srcs": attrs.list(attrs.source()),
        "deps": attrs.list(attrs.dep(), default = []),
        "edition": attrs.string(default = "2021"),
        "crate_name": attrs.option(attrs.string(), default = None),
        "proc_macro": attrs.bool(default = False),
        "features": attrs.list(attrs.string(), default = []),
    },
)
