cxx_binary(
    name = "multi-dep",
    srcs = ["main.cpp"],
    deps = [
        "//third-party:curl",
        "//third-party:zlib",
        "//third-party:openssl",
    ],
    visibility = ["PUBLIC"],
)
