load("@toolchains//:purescript.bzl", "purescript_app")

purescript_app(
    name = "halogen-todo",
    srcs = [
        "src/Main.purs",
        "src/Component/Todo.purs",
    ],
    spago_dhall = "spago.dhall",
    packages_dhall = "packages.dhall",
    index_html = "index.html",
    style_css = "style.css",
)
