// continuity codec: EVM

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — EVM ABI encoding for on-chain attestation



namespace continuity::evm {

  struct AttestCalldata {
    std::array<uint8_t, 4> selector;
    std::array<uint8_t, 32> contentHash;
    std::array<uint8_t, 32> signerIdentity;
    std::array<uint8_t, 32> issuedAt;
    std::array<uint8_t, 32> expiresAt;
    std::array<uint8_t, 32> vouchChainRoot;
  };



  std::optional<AttestCalldata> parse_attest_calldata(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::vector<uint8_t> serialize_attest_calldata(const AttestCalldata& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

} // namespace continuity::evm
