// continuity codec: GitTransport

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — Git smart transport protocol (pkt-line framing)



namespace continuity::git_transport {

constexpr uint32_t PKT_LINE_MAX_DATA = 0xffecU;



  enum class PktLineType : uint8_t { Flush = 0, Delim = 1, ResponseEnd = 2, Data = 3 };

  enum class SideBandChannel : uint8_t { PackData = 1, Progress = 2, Error = 3 };

  enum class Capability : uint8_t { MultiAck = 0, MultiAckDetailed = 1, NoDone = 2, ThinPack = 3, SideBand = 4, SideBand64k = 5, OfsDelta = 6, Shallow = 7, DeepenSince = 8, DeepenNot = 9, NoProgress = 10, IncludeTag = 11, ReportStatus = 12, DeleteRefs = 13, Quiet = 14, Filter = 15 };



} // namespace continuity::git_transport
