// continuity codec: Http3

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — HTTP/3 + QUIC + QPACK (RFC 9114, 9000, 9204)



namespace continuity::http3 {

  enum class FrameType : uint64_t { Data = 0, Headers = 1, CancelPush = 3, Settings = 4, PushPromise = 5, Goaway = 7, MaxPushId = 13 };



  struct QUICFrame {
    uint64_t frameType;
    uint64_t length;
    std::vector<uint8_t> payload;
  };



  std::optional<QUICFrame> parse_quicframe(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::vector<uint8_t> serialize_quicframe(const QUICFrame& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

} // namespace continuity::http3
