// continuity codec: Http2

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — HTTP/2 frame format (RFC 7540)



namespace continuity::http2 {

  enum class FrameType : uint8_t { Data = 0, Headers = 1, Priority = 2, RstStream = 3, Settings = 4, PushPromise = 5, Ping = 6, Goaway = 7, WindowUpdate = 8, Continuation = 9 };



  struct FrameHeader {
    uint32_t length;
    uint8_t frameType;
    uint8_t flags;
    uint32_t streamId;
  };



  std::optional<FrameHeader> parse_frame_header(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::vector<uint8_t> serialize_frame_header(const FrameHeader& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

} // namespace continuity::http2
