// continuity codec: Http

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — HTTP/1.1 request/response format (RFC 7230)



namespace continuity::http {

  enum class Method : uint8_t { Get = 0, Head = 1, Post = 2, Put = 3, Delete = 4, Connect = 5, Options = 6, Trace = 7, Patch = 8 };

  enum class TransferEncoding : uint8_t { Identity = 0, Chunked = 1, Gzip = 2, Deflate = 3, Compress = 4 };



  struct Header {
    std::vector<uint8_t> name;
    std::vector<uint8_t> value;
  };

  struct RequestLine {
    uint8_t method;
    std::vector<uint8_t> target;
    std::vector<uint8_t> version;
  };

  struct StatusLine {
    std::vector<uint8_t> version;
    uint16_t statusCode;
    std::vector<uint8_t> reasonPhrase;
  };



  std::optional<Header> parse_header(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::optional<RequestLine> parse_request_line(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::optional<StatusLine> parse_status_line(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::vector<uint8_t> serialize_header(const Header& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

  std::vector<uint8_t> serialize_request_line(const RequestLine& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

  std::vector<uint8_t> serialize_status_line(const StatusLine& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

} // namespace continuity::http
