// continuity codec: Json

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — JSON value type and recursive descent parser



namespace continuity::json {

  enum class ValueType : uint8_t { Null = 0, Bool = 1, Number = 2, String = 3, Array = 4, Object = 5 };



} // namespace continuity::json
