// continuity codec: Nix

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — Nix daemon wire protocol (nix_daemon.ksy)



namespace continuity::nix {

constexpr uint64_t WORKER_MAGIC_1 = 0x6e697863ULL;

constexpr uint64_t WORKER_MAGIC_2 = 0x6478696fULL;

constexpr uint64_t STDERR_NEXT = 0x6f6c6d67ULL;

constexpr uint64_t STDERR_READ = 0x64617461ULL;

constexpr uint64_t STDERR_WRITE = 0x64617416ULL;

constexpr uint64_t STDERR_LAST = 0x616c7473ULL;

constexpr uint64_t STDERR_ERROR = 0x63787470ULL;



  enum class WorkerOp : uint64_t { IsValidPath = 1, HasSubstitutes = 3, QueryPathHash = 4, QueryReferences = 5, QueryReferrers = 6, AddToStore = 7, BuildPaths = 9, EnsurePath = 10, AddTempRoot = 11, SetOptions = 19, CollectGarbage = 20, QueryPathInfo = 26, NarFromPath = 38, AddToStoreNar = 39, QueryMissing = 40, BuildPathsWithResults = 46 };



  struct NixString {
    std::vector<uint8_t> data;
  };

  struct StorePath {
    std::vector<uint8_t> path;
  };

  struct ClientHello {
    uint64_t magic;
  };

  struct ServerHello {
    uint64_t magic;
    uint64_t protocolVersion;
  };



  std::optional<NixString> parse_nix_string(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::optional<StorePath> parse_store_path(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::optional<ClientHello> parse_client_hello(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::optional<ServerHello> parse_server_hello(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::vector<uint8_t> serialize_nix_string(const NixString& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

  std::vector<uint8_t> serialize_store_path(const StorePath& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

  std::vector<uint8_t> serialize_client_hello(const ClientHello& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

  std::vector<uint8_t> serialize_server_hello(const ServerHello& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

} // namespace continuity::nix
