// continuity codec: Protobuf

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — Protocol Buffers wire format (protobuf.dev/encoding)



namespace continuity::protobuf {

  enum class WireType : uint8_t { Varint = 0, Fixed64 = 1, LengthDelimited = 2, Fixed32 = 5 };



  struct Tag {
    uint64_t fieldNumber;
    uint8_t wireType;
  };

  struct Field {
    uint8_t tag;
    std::vector<uint8_t> value;
  };



  std::optional<Tag> parse_tag(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::optional<Field> parse_field(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::vector<uint8_t> serialize_tag(const Tag& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

  std::vector<uint8_t> serialize_field(const Field& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

} // namespace continuity::protobuf
