// continuity codec: StateMachine

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — Protocol state machines — Nix daemon handshake + operation loop



namespace continuity::state_machine {

  enum class ServerState : uint8_t { Init = 0, Versioned = 1, Features = 2, Upgrading = 3, NixReady = 4, ReapiReady = 5, Failed = 6 };

  enum class ServerAction : uint8_t { SendServerHello = 0, SendDaemonVersion = 1, SendTrustLevel = 2, SendFeatures = 3, SendUpgradeOffer = 4, SendReapiConfig = 5, Ready = 6, Fail = 7 };

  enum class DaemonOpState : uint8_t { AwaitingOp = 0, Processing = 1, SendingStderr = 2, SendingResult = 3, OpComplete = 4, OpFailed = 5 };

  enum class Feature : uint8_t { ReapiV2 = 0, CasSha256 = 1, StreamingNar = 2, SignedNarinfo = 3 };

  enum class TrustLevel : uint8_t { Unknown = 0, Trusted = 1, Untrusted = 2 };



  struct ProtocolVersion {
    uint64_t value;
  };

  struct ReapiConfig {
    std::vector<uint8_t> instanceName;
    uint32_t digestFunction;
  };



  std::optional<ProtocolVersion> parse_protocol_version(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::optional<ReapiConfig> parse_reapi_config(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::vector<uint8_t> serialize_protocol_version(const ProtocolVersion& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

  std::vector<uint8_t> serialize_reapi_config(const ReapiConfig& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

} // namespace continuity::state_machine
