// continuity codec: Varint

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — Protobuf-style variable-length integer encoding (proven roundtrip)



namespace continuity::varint {

  struct Varint {
    uint64_t value;
  };



  std::optional<Varint> parse_varint(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::vector<uint8_t> serialize_varint(const Varint& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

} // namespace continuity::varint
