// continuity codec: Zmtp

#pragma once

#pragma once

#include <cstdint>

#include <cstring>

#include <span>

#include <vector>

#include <optional>



// Generated by Continuity — ZMTP 3.x wire format



namespace continuity::zmtp {

  struct Greeting {
    uint8_t vMajor;
    uint8_t vMinor;
    std::array<uint8_t, 20> mechanism;
    uint8_t asServer;
    std::array<uint8_t, 31> filler;
  };

  struct FrameFlags {
    uint8_t more;
    uint8_t long_;
    uint8_t command;
  };



  std::optional<Greeting> parse_greeting(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::optional<FrameFlags> parse_frame_flags(std::span<const uint8_t> bs) {
    // Generated stub — implementation links to verified Lean
    return std::nullopt;
  }

  std::vector<uint8_t> serialize_greeting(const Greeting& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

  std::vector<uint8_t> serialize_frame_flags(const FrameFlags& val) {
    // Generated stub — implementation links to verified Lean
    return {};
  }

} // namespace continuity::zmtp
