load("@toolchains//:lean.bzl", "lean_library", "lean_binary")

lean_library(
    name = "greet",
    srcs = ["MyLib/Greet.lean"],
)

lean_binary(
    name = "hello",
    srcs = ["MyLib/Main.lean"],
    deps = [":greet"],
)
