import Continuity.Codegen.Codec.Spec
import Continuity.Emit.Cpp.Ast
import Continuity.Emit.Cpp.Render

set_option autoImplicit false

namespace Continuity.Codegen.Codec

open Continuity.Emit.Cpp

private def wireTypeToCType : WireType → CType
  | .u8 => CType.intType true 8
  | .u16le | .u16be => CType.intType true 16
  | .u32le | .u32be => CType.intType true 32
  | .u64le | .u64be => CType.intType true 64
  | .bool64 => CType.bool
  | .varint => CType.intType true 64
  | .bytes n => CType.array (CType.intType true 8) n
  | .lenPrefixed => CType.template "std::vector" [CType.intType true 8]
  | .padded _ => CType.template "std::vector" [CType.intType true 8]

private def snakeCase (s : String) : String :=
  let (result, _) := s.foldl (fun ((acc, prevLower) : String × Bool) c =>
    if c.isUpper then
      let withSep := if prevLower then acc ++ "_" else acc
      (withSep ++ s!"{c.toLower}", false)
    else (acc.push c, c.isLower)
  ) ("", false)
  result

private partial def hexStr (n : Nat) : String :=
  if n == 0 then "0x0"
  else
    let rec go (n : Nat) (acc : String) : String :=
      if n == 0 then acc
      else
        let d := n % 16
        let c := if d < 10 then Char.ofNat (48 + d) else Char.ofNat (87 + d)
        go (n / 16) (s!"{c}" ++ acc)
    "0x" ++ go n ""

private def constDecl (c : ConstSpec) : CDecl :=
  let typStr := match c.wireType with
    | .u64le | .u64be => "uint64_t" | .u32le | .u32be => "uint32_t"
    | .u8 => "uint8_t" | _ => "uint64_t"
  let sfx := match c.wireType with
    | .u64le | .u64be => "ULL" | .u32le | .u32be => "U" | _ => ""
  CDecl.raw s!"constexpr {typStr} {c.name} = {hexStr c.value}{sfx};"

private def enumDecl (e : EnumSpec) : CDecl :=
  CDecl.enumClass e.name (some (wireTypeToCType e.codeType))
    (e.variants.map fun v => (v.name, some (CExpr.litUInt v.code "")))

private def structDecl (s : StructSpec) : CDecl :=
  CDecl.struct_ s.name (s.fields.map fun f => ⟨wireTypeToCType f.wireType, f.name⟩)

private def parseFnDecl (s : StructSpec) : CDecl :=
  let retType := CType.template "std::optional" [CType.named s.name]
  CDecl.func retType (s!"parse_{snakeCase s.name}")
    [⟨CType.template "std::span" [CType.const (CType.intType true 8)], "bs"⟩]
    [CStmt.comment "Generated stub — implementation links to verified Lean",
     CStmt.ret (CExpr.var "std::nullopt")]

private def serializeFnDecl (s : StructSpec) : CDecl :=
  let retType := CType.template "std::vector" [CType.intType true 8]
  CDecl.func retType (s!"serialize_{snakeCase s.name}")
    [⟨CType.ref (CType.const (CType.named s.name)), "val"⟩]
    [CStmt.comment "Generated stub — implementation links to verified Lean",
     CStmt.ret (CExpr.initList [])]

def moduleToH (m : CodecModule) : CFile :=
  let includes := [
    CDecl.pragmaOnce,
    CDecl.includeSystem "cstdint",
    CDecl.includeSystem "cstring",
    CDecl.includeSystem "span",
    CDecl.includeSystem "vector",
    CDecl.includeSystem "optional",
    CDecl.blank,
    CDecl.comment s!"Generated by Continuity — {m.doc}",
    CDecl.blank
  ]
  let body : List CDecl :=
    (m.constants.map constDecl) ++
    (if m.constants.isEmpty then [] else [CDecl.blank]) ++
    (m.enums.map enumDecl) ++
    (if m.enums.isEmpty then [] else [CDecl.blank]) ++
    (m.structs.map structDecl) ++
    (if m.structs.isEmpty then [] else [CDecl.blank]) ++
    (m.structs.map parseFnDecl) ++
    (m.structs.map serializeFnDecl)
  { header := some s!"continuity codec: {m.name}"
    pragmaOnce := true
    decls := includes ++ [CDecl.namespace_ m.namespace_ body] }

def cppCodecFiles : List (String × String) :=
  allModules.map fun m =>
    let file := moduleToH m
    (s!"codec/{snakeCase m.name}.h", renderFile file)

end Continuity.Codegen.Codec
