import Continuity.Codegen.AST.Cpp.Ast

set_option autoImplicit false

/- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

      "Mitchell's the man who made biochips work."

                                                                      — Count Zero

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

namespace Continuity.Codegen.Codec

/- stub: will be regenerated by `Codegen/Derive/Codec.lean` (Phase 2.6-2.7) -/

def cppCodecFiles : List (String × String) := []

end Continuity.Codegen.Codec
