import Continuity.Codegen.AST.Haskell.Ast

set_option autoImplicit false

/- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

      "You can go home now, Turner. We're done with you. You're good as
      new." He'd been rebuilt from the ground up, the Hosaka surgeons
      replacing what the Russians had taken, his nervous system spliced
      and re-spliced until the output matched the blueprint. He felt the
      new circuits settling into place, a kind of low-level hum that told
      him the work was sound — that the translation from pattern to flesh
      had succeeded, every instruction rendered faithfully in the target.

                                                                    — Count Zero

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

namespace Continuity.Codegen.Codec

/- stub: will be regenerated by `Codegen/Derive/Codec.lean` (Phase 2.6-2.7) -/

def hsCodecFiles : List (String × String) := []

end Continuity.Codegen.Codec
