[book]
title = "Continuity"
authors = ["Straylight Software"]
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/b7r6/continuity"
