import Continuity.Codec.Core.Box
import Continuity.Codec.Core.Bytes
import Continuity.Codec.Protocol.Protocol

set_option autoImplicit false

/- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

      "The data had never been intended for human input. It was
      generated by one machine, transmitted through an opaque
      channel, and consumed by another. The protocol had no
      affordances for readability — magic bytes, padded lengths,
      opaque opcodes — and that was the point. A human who looked
      at the wire would see nothing but noise; a worker daemon
      would see a build graph, a closure, a store path resolved
      through content-addressed hashing. The data did not need to
      be beautiful. It needed to be correct. And correctness meant
      that every byte was fixed by the hash of every other byte,
      and the whole thing either validated or it didn't."

                                                                    — Count Zero

    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

namespace Continuity.Codec.Protocol.Nix

/-
  The `Nix` daemon worker protocol.

  Frame-level encoding for `nix-daemon` communication. `NixString`
  wraps length-prefixed bytes; padding is a framing-layer concern
  managed by `nixStringWireSize` / `parseNixStringPadded`. worker
  opcodes span the full `WorkerOp` enumeration, roundtripped
  through `UInt64` codes. also includes `NAR` archive and content
  addressing types.
-/

open Continuity.Codec.Core.Box Continuity.Codec.Core.Bytes

--- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
---                                                           // wire // framing
--- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def WORKER_MAGIC_1 : UInt64 := 0x6e697863
def WORKER_MAGIC_2 : UInt64 := 0x6478696f
def STDERR_NEXT    : UInt64 := 0x6f6c6d67
def STDERR_READ    : UInt64 := 0x64617461
def STDERR_WRITE   : UInt64 := 0x64617416
def STDERR_LAST    : UInt64 := 0x616c7473
def STDERR_ERROR   : UInt64 := 0x63787470
def STDERR_START_ACTIVITY : UInt64 := 0x53545254
def STDERR_STOP_ACTIVITY  : UInt64 := 0x53544F50
def STDERR_RESULT  : UInt64 := 0x52534C54

def padSize (len : Nat) : Nat :=
  let rem := len % 8; if rem == 0 then 0 else 8 - rem

def zeroPad (n : Nat) : Bytes := ByteArray.mk (Array.replicate n 0)

theorem zeroPad_size (n : Nat) : (zeroPad n).size = n := by
  simp only [zeroPad, ByteArray.size, Array.size_replicate]

--- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
---                                                       // codec // nixString
--- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- `NixString` wraps `LenPrefixed`. the padding is a serialization detail
-- that sits outside the `Box` boundary: the daemon adds/strips padding
-- at the framing layer. the core data is just length + bytes.
structure NixString where
  data : Bytes
  bound : data.size < 2 ^ 64 := by decide

-- `nixString Box` via `isoBox` from `lenPrefixed`.
-- this gives us roundtrip and consumption for free.
def nixString : Box NixString where
  parse bs :=
    match lenPrefixed.parse bs with
    | .ok lp rest =>
      .ok ⟨lp.data, lp.bound⟩ rest
    | .fail => .fail
  serialize s :=
    lenPrefixed.serialize ⟨s.data, s.bound⟩
  roundtrip s := by
    rw [lenPrefixed.roundtrip]
  consumption s extra := by
    rw [lenPrefixed.consumption]

-- wire-level padding is handled at the framing layer.
-- these are the encode/decode functions for the padded format.
def nixStringWireSize (len : Nat) : Nat := 8 + len + padSize len

def serializeNixStringPadded (s : NixString) : Bytes :=
  u64le.serialize s.data.size.toUInt64 ++ s.data ++ zeroPad (padSize s.data.size)

def parseNixStringPadded (bs : Bytes) : ParseResult NixString :=
  u64le.parse bs |>.bind fun len rest =>
    let lenNat := len.toNat
    let totalLen := lenNat + padSize lenNat
    if h : rest.size ≥ totalLen then
      let data := rest.extract 0 lenNat
      have hbound : data.size < 2 ^ 64 := by
        have : data.size ≤ lenNat := by rw [ByteArray.size_extract]; exact Nat.min_le_left lenNat rest.size
        have : lenNat < 2 ^ 64 := UInt64.toNat_lt len; omega
      .ok ⟨data, hbound⟩ (rest.extract totalLen rest.size)
    else .fail

--- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
---                                                           // store // path
--- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

structure StorePath where
  path : NixString

def storePath : Box StorePath :=
  isoBox nixString StorePath.mk StorePath.path (fun _ => rfl) (fun a => by cases a; rfl)

--- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
---                                                        // protocol // worker
--- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

inductive WorkerOp where
  | isValidPath | hasSubstitutes | queryPathHash | queryReferences
  | queryReferrers | addToStore | addTextToStore | buildPaths
  | ensurePath | addTempRoot | addIndirectRoot | syncWithGC
  | findRoots | exportPath | queryDeriver | setOptions
  | collectGarbage | querySubstitutablePathInfo | queryDerivationOutputs
  | queryAllValidPaths | queryFailedPaths | clearFailedPaths
  | queryPathInfo | importPaths | queryDerivationOutputNames
  | queryPathFromHashPart | querySubstitutablePathInfos
  | queryValidPaths | querySubstitutablePaths | queryValidDerivers
  | optimiseStore | verifyStore | buildDerivation | addSignatures
  | narFromPath | addToStoreNar | queryMissing
  | queryDerivationOutputMap | registerDrvOutput | queryRealisation
  | addMultipleToStore | addBuildLog | buildPathsWithResults
  deriving Repr, DecidableEq

def WorkerOp.toCode : WorkerOp → UInt64
  | .isValidPath => 1 | .hasSubstitutes => 3 | .queryPathHash => 4
  | .queryReferences => 5 | .queryReferrers => 6 | .addToStore => 7
  | .addTextToStore => 8 | .buildPaths => 9 | .ensurePath => 10
  | .addTempRoot => 11 | .addIndirectRoot => 12 | .syncWithGC => 13
  | .findRoots => 14 | .exportPath => 16 | .queryDeriver => 18
  | .setOptions => 19 | .collectGarbage => 20
  | .querySubstitutablePathInfo => 21 | .queryDerivationOutputs => 22
  | .queryAllValidPaths => 23 | .queryFailedPaths => 24
  | .clearFailedPaths => 25 | .queryPathInfo => 26 | .importPaths => 27
  | .queryDerivationOutputNames => 28 | .queryPathFromHashPart => 29
  | .querySubstitutablePathInfos => 30 | .queryValidPaths => 31
  | .querySubstitutablePaths => 32 | .queryValidDerivers => 33
  | .optimiseStore => 34 | .verifyStore => 35 | .buildDerivation => 36
  | .addSignatures => 37 | .narFromPath => 38 | .addToStoreNar => 39
  | .queryMissing => 40 | .queryDerivationOutputMap => 41
  | .registerDrvOutput => 42 | .queryRealisation => 43
  | .addMultipleToStore => 44 | .addBuildLog => 45
  | .buildPathsWithResults => 46

def WorkerOp.fromCode : UInt64 → Option WorkerOp
  |  1 => some .isValidPath     |  3 => some .hasSubstitutes
  |  4 => some .queryPathHash   |  5 => some .queryReferences
  |  6 => some .queryReferrers  |  7 => some .addToStore
  |  8 => some .addTextToStore  |  9 => some .buildPaths
  | 10 => some .ensurePath      | 11 => some .addTempRoot
  | 12 => some .addIndirectRoot | 13 => some .syncWithGC
  | 14 => some .findRoots       | 16 => some .exportPath
  | 18 => some .queryDeriver    | 19 => some .setOptions
  | 20 => some .collectGarbage  | 21 => some .querySubstitutablePathInfo
  | 22 => some .queryDerivationOutputs | 23 => some .queryAllValidPaths
  | 24 => some .queryFailedPaths | 25 => some .clearFailedPaths
  | 26 => some .queryPathInfo   | 27 => some .importPaths
  | 28 => some .queryDerivationOutputNames | 29 => some .queryPathFromHashPart
  | 30 => some .querySubstitutablePathInfos | 31 => some .queryValidPaths
  | 32 => some .querySubstitutablePaths | 33 => some .queryValidDerivers
  | 34 => some .optimiseStore   | 35 => some .verifyStore
  | 36 => some .buildDerivation | 37 => some .addSignatures
  | 38 => some .narFromPath     | 39 => some .addToStoreNar
  | 40 => some .queryMissing    | 41 => some .queryDerivationOutputMap
  | 42 => some .registerDrvOutput | 43 => some .queryRealisation
  | 44 => some .addMultipleToStore | 45 => some .addBuildLog
  | 46 => some .buildPathsWithResults | _ => none

theorem workerOp_roundtrip (op : WorkerOp) : WorkerOp.fromCode op.toCode = some op := by
  cases op <;> rfl

--- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
---                                                           // archive // nar
--- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def NAR_MAGIC : String := "nix-archive-1"

inductive NarEntry where
  | regular (executable : Bool) (contents : Bytes)
  | directory (entries : List (String × NarEntry))
  | symlink (target : String)

inductive HashAlgorithm where | sha256 | sha512 | sha1 | md5 deriving Repr, DecidableEq
inductive ContentAddressMethod where | flat | nar | text | git deriving Repr, DecidableEq

end Continuity.Codec.Protocol.Nix
